export default {
  "0480b142": [() => import(/* webpackChunkName: "0480b142" */ "@site/docs/faq.md"), "@site/docs/faq.md", require.resolveWeak("@site/docs/faq.md")],
  "10aaceff": [() => import(/* webpackChunkName: "10aaceff" */ "@site/docs/student-scholarship.md"), "@site/docs/student-scholarship.md", require.resolveWeak("@site/docs/student-scholarship.md")],
  "138e0e15": [() => import(/* webpackChunkName: "138e0e15" */ "@generated/@easyops-cn/docusaurus-search-local/default/__plugin.json"), "@generated/@easyops-cn/docusaurus-search-local/default/__plugin.json", require.resolveWeak("@generated/@easyops-cn/docusaurus-search-local/default/__plugin.json")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1a4e3797": [() => import(/* webpackChunkName: "1a4e3797" */ "@theme/SearchPage"), "@theme/SearchPage", require.resolveWeak("@theme/SearchPage")],
  "2bb51d77": [() => import(/* webpackChunkName: "2bb51d77" */ "@site/docs/apa-style-guide.md"), "@site/docs/apa-style-guide.md", require.resolveWeak("@site/docs/apa-style-guide.md")],
  "3bb011eb": [() => import(/* webpackChunkName: "3bb011eb" */ "@site/docs/article-manuscripts.md"), "@site/docs/article-manuscripts.md", require.resolveWeak("@site/docs/article-manuscripts.md")],
  "4e9ca076": [() => import(/* webpackChunkName: "4e9ca076" */ "@site/docs/templates.md"), "@site/docs/templates.md", require.resolveWeak("@site/docs/templates.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "7a62146d": [() => import(/* webpackChunkName: "7a62146d" */ "@generated/docusaurus-plugin-content-docs/default/p/jkw-guide-1c9.json"), "@generated/docusaurus-plugin-content-docs/default/p/jkw-guide-1c9.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/jkw-guide-1c9.json")],
  "85467737": [() => import(/* webpackChunkName: "85467737" */ "@site/docs/wskw-chronicles.md"), "@site/docs/wskw-chronicles.md", require.resolveWeak("@site/docs/wskw-chronicles.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "abde8ea5": [() => import(/* webpackChunkName: "abde8ea5" */ "@site/docs/massengale-papers.md"), "@site/docs/massengale-papers.md", require.resolveWeak("@site/docs/massengale-papers.md")],
  "c377a04b": [() => import(/* webpackChunkName: "c377a04b" */ "@site/docs/index.md"), "@site/docs/index.md", require.resolveWeak("@site/docs/index.md")],
  "d2838e7d": [() => import(/* webpackChunkName: "d2838e7d" */ "@site/docs/submission-guidelines.md"), "@site/docs/submission-guidelines.md", require.resolveWeak("@site/docs/submission-guidelines.md")],};
